version: '3.8'

services:
  app:
    container_name: cinepik-watchlist
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - cinepik-network

  db:
    container_name: cinepik-watchlist-db
    image: postgres:15.5-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - cinepik-network

volumes:
  postgres_data:
  node_modules:


networks:
  cinepik-network:
    name: cinepik-network
    external: true
