apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-watchlist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinepik-watchlist
  template:
    metadata:
      labels:
        app: cinepik-watchlist
    spec:
      containers:
        - image: sebam/cinepik-watchlist:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
          name: cinepik-watchlist
          env:
            - name: NODE_PORT
              value: '3002'
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_CLIENT_ID
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DATABASE_URL
            - name: RECOMMENDATION_SERVICE_URL
              value: 'http://cinepik-recommendation-engine:3003'
            - name: MOVIES_RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: watchlist-credentials
                  key: MOVIES_RAPID_API_KEY
          ports:
            - containerPort: 3002
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
